version: "3.7"
services:
  s3:
    image: localstack/localstack:latest
    hostname: localstack
    networks:
      - tx-net
    ports:
      - "4566-4599:4566-4599"
      - "8055:8080"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8055
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - /tmp/localstack:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./bin:/docker-entrypoint-initaws.d

networks:
  tx-net:
    external: true

