---
version: "3.9"

x-common-variables: &common-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-123}
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-123}
  QUEUE_PREFIX: "dev-"
  RESTRICT_GITEA_URL: ${RESTRICT_GITEA_URL-false}
  REDIS_HOSTNAME: ${REDIS_HOSTNAME-redis}
  DEBUG_MODE: ${DEBUG_MODE-true}
  REDIS_URL: ${REDIS_URL-redis://redis:6379}
  AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL-http://localstack:4566}
  DB_ENDPOINT: ${DB_ENDPOINT-sqlite:///:memory:}
  TX_DATABASE_PW: "123"
  GITEA_URL: ${GITEA_URL-http://dcs}
  GOGS_USER_TOKEN: "123"
  DCS_PORT: ${DCS_PORT-5555}
  DOOR43_PREVIEW_PORT: ${DOOR43_PREVIEW_PORT-5556}

services:
  redis:
    image: redis:alpine
    networks: 
      - tx-net

  localstack:
    image: localstack/localstack:latest
    environment:
      - SERVICES=s3,cloudwatch
      - DEBUG=${DEBUG_MODE-1}
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8055
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    networks:
      - tx-net
    ports:
      - "4566:4566"
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/bin:/docker-entrypoint-initaws.d"

  d43enqueue:
    build:
      context: ./door43-enqueue-job/enqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    networks:
      - tx-net
    depends_on:
      - redis
      - localstack

  d43proxy:
    image: nginx:latest
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    volumes:
      - "${PWD}/door43-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro"
    networks:
      - tx-net
    depends_on:
      - d43enqueue
      
  door43-job-handler:
    image: python:3
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings --name D43_Dev_JobHandler"
    environment: *common-variables
    volumes:
      - ${PWD}/door43-job-handler:/scripts
      - door43_u:/site/u
    networks:
      - tx-net
    depends_on:
      - d43proxy

  txenqueue:
    build:
      context: ./tx-enqueue-job/tXenqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    networks:
      - tx-net
    depends_on:
      - redis
      - localstack

  txproxy:
    image: nginx:latest
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    volumes:
      - ${PWD}/tx-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    networks:
      - tx-net
    depends_on:
      - txenqueue
    
  tx-job-handler:
    image: python:3
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings --name tX_Dev_Job_Handler"
    environment: *common-variables
    volumes:
      - ${PWD}/tx-job-handler:/scripts
    networks:
      - tx-net
    depends_on:
      - txproxy

  dcs:
    build:
      context: ./dcs
      args:
        - DOOR43_PREVIEW_PORT=${DOOR43_PREVIEW_PORT-5556}
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - ${DCS_PORT-5555}:80
      - "222:22"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${DCS_PORT-5555}:80
      - "222:22"
    networks:
      - tx-net
  
  door43.org:
    build: ./door43.org
    ports:
      - "${LISTEN_IP:-127.0.0.1}:${DOOR43_PREVIEW_PORT-5556}:80"
    volumes:
      - door43_u:/site/u
    networks:
      - tx-net
    depends_on:
      - localstack


networks:
  tx-net:
    name: tx-net
    external: false


volumes:
  door43_u:
    name: door43_u  
    external: false
