---
version: "3.9"

x-common-variables: &common-variables
  AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID-123}
  QUEUE_PREFIX: "dev-"
  AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY-123}
  GITEA_URL: ${GITEA_URL-http://dcs}
  RESTRICT_GITEA_URL: ${RESTRICT_GITEA_URL-false}
  REDIS_HOSTNAME: ${REDIS_HOSTNAME-redis}
  DEBUG_MODE: ${DEBUG_MODE-true}
  REDIS_URL: ${REDIS_URL-redis://redis:6379}
  AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL-http://localstack:4566}

services:
  redis:
    image: redis:alpine
    networks: 
      - tx-net

  localstack:
    image: localstack/localstack:latest
    networks:
      - tx-net
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,cloudwatch
      - DEBUG=${DEBUG_MODE-1}
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8055
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - /tmp/localstack/data:/tmp/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./s3/bin:/docker-entrypoint-initaws.d

  d43enqueue:
    build:
      context: ./door43-enqueue-job/enqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    networks:
      - tx-net
    depends_on:
      - redis

  d43proxy:
    image: nginx:latest
    volumes:
      - ${PWD}/door43-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - tx-net
    depends_on:
      - d43enqueue
      
  d43-job-handler:
    image: python:3
    environment: *common-variables
    volumes:
      - ${PWD}/door43-job-handler:/scripts
      - door43_u:/site/u
    networks:
      - tx-net
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings --name D43_Dev_JobHandler"
    depends_on:
      - d43proxy

  txenqueue:
    build:
      context: ./tx-enqueue-job/tXenqueue
      dockerfile: Dockerfile-developBranch
    environment: *common-variables
    networks:
      - tx-net
    depends_on:
      - redis

  txproxy:
    image: nginx:latest
    volumes:
      - ${PWD}/tx-enqueue-job/proxyConf/dev-nginx.conf:/etc/nginx/conf.d/mysite.template:ro
    environment:
      - ALLOWED_IPS=${ALLOWED_IPS:-0.0.0.0/0}
    command: /bin/sh -c "envsubst '$$ALLOWED_IPS' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - tx-net
    depends_on:
      - txenqueue
    
  tx-job-handler:
    image: python:3
    environment: *common-variables
    volumes:
      - ${PWD}/tx-job-handler:/scripts
    networks:
      - tx-net
    command: /bin/bash -c "cd /scripts; pip install -r requirements.txt; rq worker --config rq_settings --name tX_Dev_Job_Handler"
    depends_on:
      - txproxy

  dcs:
    image: unfoldingword/dcs:latest
    volumes:
      - ./dcs/data:/data 
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - 3000:3000
  
  door43.org:
    container_name: door43.org
    build:
      context: ./door43.org
      dockerfile: Dockerfile
    volumes:
      - door43_u:/site/u
    networks:
      - tx-net
    ports:
      - "${LISTEN_IP:-127.0.0.1}:3001:80"

networks:
  tx-net:
    name: tx-net
    external: false

volumes:
  door43_u:
    external: true
    name: door43_u  
  dcs-data:
    external: true
    name: dcs-data
