version: "3"

networks:
  default:
    external:
      name: tx-net

services:
  server:
    image: unfoldingword/dcs:latest
    container_name: dcs
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:80"
      - "222:22"

